# Generated by Django 2.2.4 on 2019-12-24 03:43

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HubunganKeluarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hubungan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JenisData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jd', models.CharField(max_length=50)),
                ('tabel_jd', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nama_jd'],
            },
        ),
        migrations.CreateModel(
            name='Jenjang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.IntegerField()),
                ('pendidikan', models.CharField(max_length=100)),
                ('lulus', models.CharField(max_length=4)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JenjangKarir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.IntegerField()),
                ('divisi', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=100)),
                ('perusahaan', models.CharField(max_length=100)),
                ('thnawal', models.CharField(max_length=20)),
                ('thnakhir', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JenjangPendidikan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenjang', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(default='', max_length=32, null=True)),
                ('nik', models.CharField(max_length=20)),
                ('nama_karyawan', models.CharField(max_length=50)),
                ('alias_karyawan', models.CharField(max_length=50)),
                ('tp_lahir_karyawan', models.CharField(max_length=50)),
                ('tg_lahir_karyawan', models.CharField(max_length=50)),
                ('jn_kelamin_karyawan', models.CharField(choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], default='Laki-Laki', max_length=1)),
                ('status_karyawan', models.CharField(choices=[('Single', 'Lajang'), ('Widow', 'Duda/Janda'), ('Maried', 'Kawin')], default='Single', max_length=1)),
                ('tanggungan_karyawan', models.IntegerField(null=True)),
                ('alamat_karyawan', models.CharField(max_length=256)),
                ('hp_karyawan', models.CharField(max_length=13)),
                ('jabatan_karyawan', models.CharField(max_length=100)),
                ('tmt_masuk_karyawan', models.DateField(auto_now_add=True, null=True)),
                ('email_karyawan', models.EmailField(max_length=254)),
                ('npwp_karyawan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KategoriData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori_data', models.CharField(max_length=50)),
                ('keterangan_kategori_data', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kemampuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.IntegerField()),
                ('kemampuan', models.CharField(max_length=100)),
                ('tingkat', models.IntegerField()),
                ('grade', models.CharField(max_length=20)),
                ('serfikat', models.IntegerField()),
                ('tahun', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('kunciutama', models.CharField(max_length=15)),
                ('kunciawal', models.CharField(max_length=15)),
                ('kunciakhir', models.CharField(max_length=15)),
                ('deskripsi', models.TextField(blank=True)),
                ('jenis_data', models.CharField(blank=True, max_length=50)),
                ('tanggal_buat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_edit', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='KriteriaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_kriteria', models.IntegerField()),
                ('nama_tabel', models.IntegerField()),
                ('id_data', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NonFormalList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pekerjaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pekerjaan', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelanggan', models.CharField(max_length=50)),
                ('alamat_pelanggan', models.CharField(max_length=256)),
                ('hp_pelanggan', models.CharField(max_length=13)),
                ('email_pelanggan', models.EmailField(max_length=254)),
                ('npwp_pelanggan', models.IntegerField()),
                ('jenis_pelanggan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PengalamanKerja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.IntegerField()),
                ('perusahaan', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('usaha', models.CharField(max_length=50)),
                ('posisi', models.CharField(max_length=50)),
                ('alasan', models.CharField(max_length=100)),
                ('thnawal', models.CharField(max_length=20)),
                ('thnakhir', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
            },
        ),
        migrations.CreateModel(
            name='Suplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_suplier', models.CharField(max_length=50)),
                ('alamat_suplier', models.CharField(max_length=256)),
                ('hp_suplier', models.CharField(max_length=13)),
                ('email_suplier', models.EmailField(max_length=254)),
                ('npwp_suplier', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='J:\\azharmedia\\akselerasi\\galeri\\uploads\\users'), upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_produk', models.CharField(max_length=100)),
                ('barcode_produk', models.CharField(max_length=100, null=True)),
                ('nama_produk', models.CharField(max_length=50)),
                ('suplier_produk', models.CharField(max_length=50)),
                ('harga_produk', models.CharField(max_length=50)),
                ('brand_produk', models.CharField(max_length=50)),
                ('kategori', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='excels.Kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Pendidikan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.IntegerField()),
                ('jurusan', models.CharField(max_length=25)),
                ('institusi', models.CharField(max_length=100)),
                ('lulus', models.CharField(max_length=4)),
                ('jenjang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excels.JenjangPendidikan')),
            ],
        ),
        migrations.CreateModel(
            name='NonFormalPendidikan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.IntegerField()),
                ('lembaga', models.CharField(max_length=100)),
                ('jurusan', models.CharField(max_length=50)),
                ('tahun', models.CharField(max_length=4)),
                ('jenis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excels.NonFormalList')),
            ],
        ),
        migrations.CreateModel(
            name='Keluarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=24)),
                ('nama', models.CharField(max_length=100)),
                ('tempat', models.CharField(max_length=100)),
                ('tanggal', models.CharField(max_length=20)),
                ('jenis', models.CharField(choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], default='Laki-Laki', max_length=1)),
                ('agama', models.CharField(max_length=15)),
                ('alamat', models.TextField(null=True)),
                ('status', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hubungan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excels.HubunganKeluarga')),
                ('pekerjaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excels.Pekerjaan')),
            ],
        ),
        migrations.CreateModel(
            name='Kamus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frasa', models.CharField(max_length=100)),
                ('keterangan', models.CharField(max_length=100)),
                ('kategori_data', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='excels.KategoriData')),
            ],
        ),
    ]
