# Generated by Django 2.2.4 on 2019-12-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keluarga',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='keluarga',
            name='telp',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
