# Generated by Django 2.2.4 on 2019-12-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excels', '0002_auto_20191224_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='kemampuan',
            name='nosertifikat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nonformalpendidikan',
            name='nosertifikat',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
