# Generated by Django 2.2.4 on 2019-12-28 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excels', '0004_auto_20191228_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divisi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisi', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='karyawan',
            name='tanggal_buat',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='tanggal_edit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='wajib_pajak',
            field=models.CharField(choices=[('Ya', 'Ya'), ('Tidak', 'Tidak')], default='Tidak', max_length=1),
        ),
        migrations.AddField(
            model_name='pelanggan',
            name='pkp',
            field=models.CharField(choices=[('Ya', 'Ya'), ('Tidak', 'Tidak')], default='Tidak', max_length=1),
        ),
        migrations.AddField(
            model_name='pelanggan',
            name='tanggal_buat',
            field=models.DateTimeField(auto_now_add=True, null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='pelanggan',
            name='tanggal_edit',
            field=models.DateTimeField(blank=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='suplier',
            name='pkp',
            field=models.CharField(choices=[('Ya', 'Ya'), ('Tidak', 'Tidak')], default='Tidak', max_length=1),
        ),
        migrations.AddField(
            model_name='suplier',
            name='tanggal_buat',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='suplier',
            name='tanggal_edit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='divisi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='excels.Divisi'),
        ),
        migrations.AddField(
            model_name='pelanggan',
            name='divisi_pelanggan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='excels.Divisi'),
        ),
        migrations.AddField(
            model_name='suplier',
            name='divisi_suplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='excels.Divisi'),
        ),
    ]
