# Generated by Django 2.2.4 on 2019-12-31 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excels', '0005_auto_20191228_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namadata', models.CharField(max_length=50)),
                ('keterangan', models.CharField(max_length=100)),
            ],
        ),
    ]
