# Generated by Django 2.2.4 on 2020-01-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excels', '0006_grupdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='kamus',
            name='hasil',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
