# Generated by Django 2.2.4 on 2020-01-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excels', '0007_kamus_hasil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggan',
            name='jenis_pelanggan',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='npwp_pelanggan',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='suplier',
            name='npwp_suplier',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
