# Generated by Django 2.2.4 on 2020-01-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excels', '0008_auto_20200102_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisi',
            name='divisi',
            field=models.CharField(max_length=50),
        ),
    ]
