# Generated by Django 2.2.4 on 2020-01-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excels', '0009_auto_20200102_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisi',
            name='keterangan',
            field=models.TextField(null=True),
        ),
       
    ]
