# Generated by Django 2.2.4 on 2020-01-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excels', '0010_auto_20200102_1051'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='divisi',
            constraint=models.UniqueConstraint(fields=('divisi',), name='divisi'),
        ),
    ]
