# Generated by Django 2.2.4 on 2020-01-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excels', '0012_auto_20200103_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jenisdata',
            options={},
        ),
        migrations.AlterField(
            model_name='jenisdata',
            name='nama_jd',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='grupdata',
            constraint=models.UniqueConstraint(fields=('namadata',), name='namadata'),
        ),
        migrations.AddConstraint(
            model_name='jenisdata',
            constraint=models.UniqueConstraint(fields=('nama_jd',), name='nama_jd'),
        ),
    ]
