# Generated by Django 2.2.4 on 2020-01-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20200115_1352'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='jabatan',
            constraint=models.UniqueConstraint(fields=('namajabatan',), name='namajabatan'),
        ),
    ]
