# Generated by Django 2.2.4 on 2020-01-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_auto_20200115_1409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Karir',
            new_name='Pangkat',
        ),
        migrations.RemoveConstraint(
            model_name='pangkat',
            name='karir',
        ),
        migrations.RenameField(
            model_name='pangkat',
            old_name='karir',
            new_name='pangkat',
        ),
        migrations.AddConstraint(
            model_name='pangkat',
            constraint=models.UniqueConstraint(fields=('pangkat',), name='pangkat'),
        ),
    ]
