# Generated by Django 2.2.4 on 2019-11-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField()),
                ('module', models.IntegerField()),
                ('url', models.CharField(max_length=100)),
                ('menu_name', models.CharField(max_length=100)),
                ('menu_type', models.CharField(max_length=10)),
                ('role_id', models.CharField(max_length=100)),
                ('deep', models.IntegerField()),
                ('ordering', models.IntegerField()),
                ('position', models.CharField(choices=[('top', 'top'), ('sidebar', 'sidebar'), ('both', 'both')], default='top', max_length=1)),
                ('menu_icons', models.CharField(max_length=30)),
                ('active', models.IntegerField()),
                ('menu_lang', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100)),
                ('module_title', models.CharField(max_length=100)),
                ('module_note', models.CharField(max_length=255)),
                ('module_author', models.CharField(max_length=100)),
                ('module_desc', models.TextField()),
                ('module_db_key', models.CharField(max_length=100)),
                ('module_type', models.CharField(choices=[('master', 'master'), ('report', 'report'), ('proccess', 'proccess'), ('core', 'core'), ('generic', 'generic'), ('addon', 'addon')], default='proccess', max_length=1)),
                ('module_config', models.TextField()),
                ('module_lang', models.TextField()),
            ],
        ),
    ]
