# Generated by Django 2.2.4 on 2020-01-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_remove_kecamatan_jenis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('user', models.IntegerField()),
                ('ip', models.CharField(max_length=20)),
                ('process', models.CharField(max_length=100)),
                ('log_error', models.TextField()),
            ],
        ),
    ]
