# Generated by Django 2.2.4 on 2020-01-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_log'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='app_config',
            constraint=models.UniqueConstraint(fields=('key',), name='key'),
        ),
    ]
